export const USERS_CLEAR = 'USERS_CLEAR';
export const USERS_DELETE = 'USERS_DELETE';

export const USERS_GET_START = 'USERS_GET_START';
export const USERS_GET_SUCCESS = 'USERS_GET_SUCCESS';
export const USERS_GET_ERROR = 'USERS_GET_ERROR';

export const DETAILS_FIND = 'DETAILS_FIND';

export const DETAILS_GET_START = 'DETAILS_GET_START';
export const DETAILS_GET_SUCCESS = 'DETAILS_GET_SUCCESS';
export const DETAILS_GET_ERROR = 'DETAILS_GET_ERROR';
